import Head from 'next/head'
import { AppLayout } from 'components/AppLayout';
export default function Home() {
  return (
    <div>
      <Head>
        <title>NMKZ Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </AppLayout>
    </div>
  )
}
