import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { AppLayout } from 'components/AppLayout';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NMKZ Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <nav>
          <Link href='/timeline'>
            to TimeLine
          </Link>
        </nav>
      </AppLayout>
    </div>
  )
}
